version: "3"
services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - inpi-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - inpi-network
    depends_on:
      - redis

  worker:
    build: .
    privileged: true
    command: >
        /bin/sh -c "python3.8 manage.py run_worker"
    environment:
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME_TEST: '/volume_inpi/'
    volumes:
      - /run/media/julia/DATA/INPI/:/volume_test
    networks:
      - inpi-network
    depends_on:
      - redis

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3.8 /src/manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME_TEST: '/volume_inpi/'
    volumes:
      - /run/media/julia/DATA/INPI/:/volume_test
    networks:
      - inpi-network
    depends_on:
      - worker

networks:
  inpi-network:
    driver: bridge

volumes:
  volume_test:

